In [1]:
REPO_DIR = "/Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM"
DATA_DIR = "/Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM/data/YahooAnswer"

print("DATA_DIR:", DATA_DIR)
print("REPO_DIR:", REPO_DIR)

DATA_DIR: /Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM/data/YahooAnswer
REPO_DIR: /Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM

In [2]:
import os
import numpy as np
import scipy.sparse as sp

def load_vocab(path):
    with open(path, "r", encoding="utf-8") as f:
        return [line.strip() for line in f if line.strip()]

def load_bow(path):
    X = sp.load_npz(path).astype(np.float32)  
    return X.toarray()                        


def load_word_embeddings(path):
    W = sp.load_npz(path)                 
    return W.astype(np.float32).toarray() 


train_bow = load_bow(os.path.join(DATA_DIR, "train_bow.npz"))
test_bow  = load_bow(os.path.join(DATA_DIR, "test_bow.npz"))
vocab     = load_vocab(os.path.join(DATA_DIR, "vocab.txt"))
word_emb  = load_word_embeddings(os.path.join(DATA_DIR, "word_embeddings.npz"))

print("train_bow:", train_bow.shape)
print("test_bow :", test_bow.shape)
print("word_emb :", word_emb.shape)
print("vocab    :", len(vocab))

train_bow: (10000, 5000)
test_bow : (2500, 5000)
word_emb : (5000, 200)
vocab    : 5000

- lit les matrices bag-of-words d’entraînement et de test et les convertit en tableaux denses NumPy
- lit la liste des mots (vocabulaire) depuis vocab.txt
- lit les embeddings de mots et les convertit aussi en tableau NumPy 
- imprime les shapes de ces trois matrices et la taille du vocabulaire

 Setup + seed

In [3]:
!pip install torch torchvision torchaudio

Requirement already satisfied: torch in /Users/hydersidra/opt/anaconda3/lib/python3.9/site-packages (2.2.2)
Requirement already satisfied: torchvision in /Users/hydersidra/opt/anaconda3/lib/python3.9/site-packages (0.17.2)
Requirement already satisfied: torchaudio in /Users/hydersidra/opt/anaconda3/lib/python3.9/site-packages (2.2.2)
Requirement already satisfied: filelock in /Users/hydersidra/opt/anaconda3/lib/python3.9/site-packages (from torch) (3.6.0)
Requirement already satisfied: fsspec in /Users/hydersidra/opt/anaconda3/lib/python3.9/site-packages (from torch) (2022.7.1)
Requirement already satisfied: jinja2 in /Users/hydersidra/opt/anaconda3/lib/python3.9/site-packages (from torch) (2.11.3)
Requirement already satisfied: typing-extensions>=4.8.0 in /Users/hydersidra/opt/anaconda3/lib/python3.9/site-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /Users/hydersidra/opt/anaconda3/lib/python3.9/site-packages (from torch) (2.8.4)
Requirement already satisfied: sympy in /Users/hydersidra/opt/anaconda3/lib/python3.9/site-packages (from torch) (1.10.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /Users/hydersidra/opt/anaconda3/lib/python3.9/site-packages (from torchvision) (9.2.0)
Requirement already satisfied: numpy in /Users/hydersidra/opt/anaconda3/lib/python3.9/site-packages (from torchvision) (1.23.5)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/hydersidra/opt/anaconda3/lib/python3.9/site-packages (from jinja2->torch) (2.0.1)
Requirement already satisfied: mpmath>=0.19 in /Users/hydersidra/opt/anaconda3/lib/python3.9/site-packages (from sympy->torch) (1.2.1)

In [4]:
import os, random
import numpy as np
import torch

REPO_DIR = "/Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM/ECRTM" 
DATA_ROOT = "/Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM/data"
OUT_DIR = "/Users/hydersidra/Documents/Master/PPD/ECRTM_runs/ECRTM"
os.makedirs(OUT_DIR, exist_ok=True)

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False  
    return seed

SEED = set_seed(42)
print("SEED =", SEED)

SEED = 42

Map dataset → YAML (leurs configs)

In [5]:
CONFIGS = {
  "20NG": "/Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM/ECRTM/configs/model/ECRTM_20NG.yaml",
  "AGNews": "/Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM/ECRTM/configs/model/ECRTM_AGNews.yaml",
  "IMBD": "/Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM/ECRTM/configs/model/ECRTM_IMDB.yaml",
  "YahooAnswer": "/Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM/ECRTM/configs/model/ECRTM_YahooAnswer.yaml",
}

Imports modèle + utilitaires

In [6]:
import sys
import yaml
import scipy.io
import scipy.sparse as sp
from types import SimpleNamespace
from torch.utils.data import DataLoader, TensorDataset

sys.path.append(REPO_DIR)
from models.ECRTM import ECRTM

def load_cfg(path):
    with open(path, "r") as f:
        return yaml.safe_load(f)  

def load_vocab(path):
    with open(path, "r", encoding="utf-8") as f:
        return [line.strip() for line in f if line.strip()]

def load_bow_npz(path):
    X = sp.load_npz(path).astype(np.float32)  
    return X.toarray()                       

def load_word_emb_npz(path):
    W = sp.load_npz(path)                 
    return W.astype(np.float32).toarray()

- `load_cfg` : ouvre un fichier de config YAML et le transforme en objet Python
- `load_vocab` : lit le vocabulaire (une liste de mots)
- `load_bow_npz` : charge la matrice bag‑of‑words et la met en matrice NumPy   
- `load_word_emb_npz` : charge les embeddings de mots et les met en matrice NumPy

Fonctions: build args + infer theta

In [7]:
def build_args_from_yaml(cfg, K, vocab_size, word_emb):
    cfg = dict(cfg)  # copie
    cfg["num_topic"] = K
    cfg["vocab_size"] = vocab_size
    cfg["word_embeddings"] = word_emb
    return SimpleNamespace(**cfg)

def infer_theta(model, bow_np, device, batch_size=256):
    model.eval()
    thetas = []
    with torch.no_grad():
        X = torch.from_numpy(bow_np).float()
        loader = DataLoader(TensorDataset(X), batch_size=batch_size, shuffle=False)
        for (bow,) in loader:
            bow = bow.to(device)
            theta = model.get_theta(bow)  
            thetas.append(theta.cpu().numpy())
    return np.vstack(thetas)

build_args_from_yaml : prend la config YAML et y ajoute K, la taille du vocab et les embeddings, pour créer un objet args prêt à donner au modèle.

infer_theta : fait passer tous tes bag‑of‑words dans le modèle (par batch) et renvoie la matrice θ = distribution de topics pour chaque document.

 run complet: train_one(dataset, K)

In [8]:
from tqdm.auto import tqdm

def train_one(dataset, K, seed=42):
    set_seed(seed)

    data_dir = os.path.join(DATA_ROOT, dataset)
    cfg = load_cfg(CONFIGS[dataset])

    # Hyperparams depuis YAML
    epochs = int(cfg["epochs"])
    batch_size = int(cfg["batch_size"])
    lr = float(cfg["learning_rate"])

    # Data
    train_bow = load_bow_npz(os.path.join(data_dir, "train_bow.npz"))
    test_bow  = load_bow_npz(os.path.join(data_dir, "test_bow.npz"))
    vocab     = load_vocab(os.path.join(data_dir, "vocab.txt"))
    word_emb  = load_word_emb_npz(os.path.join(data_dir, "word_embeddings.npz"))

    V = train_bow.shape[1]
    assert V == test_bow.shape[1] == len(vocab) == word_emb.shape[0], "Mismatch vocab sizes"


    args = build_args_from_yaml(cfg, K=K, vocab_size=V, word_emb=word_emb)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = ECRTM(args).to(device)
    opt = torch.optim.Adam(model.parameters(), lr=lr)

    X = torch.from_numpy(train_bow).float()
    loader = DataLoader(TensorDataset(X), batch_size=batch_size, shuffle=True)

    epoch_bar = tqdm(range(1, epochs + 1), desc=f"{dataset} | K={K} | seed={seed}", position=0)
    for epoch in epoch_bar:
        model.train()
        total_loss = 0.0

        batch_bar = tqdm(loader, desc=f"epoch {epoch}/{epochs}", leave=False, position=1)
        for (bow,) in batch_bar:
            bow = bow.to(device)
            rst = model(bow)
            loss = rst["loss"]

            opt.zero_grad()
            loss.backward()
            opt.step()

            l = float(loss.detach().cpu())
            total_loss += l
            batch_bar.set_postfix(loss=l)

        epoch_bar.set_postfix(avg_loss=total_loss / len(loader))

    model.eval()
    with torch.no_grad():
        beta = model.get_beta().cpu().numpy()

    train_theta = infer_theta(model, train_bow, device=device, batch_size=256)
    test_theta  = infer_theta(model, test_bow,  device=device, batch_size=256)

    out_path = os.path.join(OUT_DIR, f"{dataset}_ECRTM_K{K}_seed{seed}.mat")
    scipy.io.savemat(out_path, {"beta": beta, "train_theta": train_theta, "test_theta": test_theta})
    print("Saved:", out_path)
    return out_path

- Elle charge les données + la config.
- Elle entraîne le modèle ECRTM (boucle d’epochs).
- Elle calcule les matrices beta (topics–mots) et theta (doc–topic pour train et test).
- Elle écrit tout ça dans un fichier .mat et

20NG

In [ ]:
#for K in [20, 50, 100]:
#    train_one("20NG", K=K, seed=42)

IMDB

In [ ]:
#for K in [20, 50, 100]:
    #train_one("IMDB", K=K, seed=42)

AGNews

In [ ]:
for K in [20, 50, 100]:
    train_one("AGNews", K=K, seed=42)

YahooAnswer

In [9]:
for K in [20, 50, 100]:
    train_one("YahooAnswer", K=K, seed=42)

YahooAnswer | K=20 | seed=42:   0%|          | 0/500 [00:00<?, ?it/s]

epoch 1/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 2/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 3/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 4/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 5/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 6/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 7/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 8/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 9/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 10/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 11/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 12/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 13/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 14/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 15/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 16/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 17/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 18/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 19/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 20/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 21/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 22/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 23/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 24/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 25/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 26/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 27/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 28/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 29/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 30/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 31/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 32/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 33/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 34/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 35/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 36/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 37/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 38/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 39/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 40/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 41/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 42/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 43/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 44/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 45/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 46/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 47/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 48/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 49/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 50/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 51/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 52/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 53/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 54/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 55/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 56/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 57/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 58/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 59/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 60/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 61/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 62/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 63/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 64/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 65/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 66/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 67/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 68/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 69/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 70/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 71/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 72/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 73/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 74/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 75/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 76/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 77/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 78/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 79/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 80/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 81/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 82/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 83/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 84/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 85/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 86/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 87/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 88/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 89/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 90/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 91/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 92/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 93/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 94/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 95/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 96/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 97/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 98/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 99/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 100/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 101/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 102/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 103/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 104/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 105/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 106/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 107/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 108/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 109/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 110/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 111/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 112/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 113/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 114/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 115/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 116/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 117/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 118/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 119/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 120/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 121/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 122/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 123/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 124/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 125/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 126/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 127/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 128/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 129/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 130/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 131/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 132/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 133/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 134/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 135/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 136/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 137/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 138/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 139/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 140/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 141/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 142/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 143/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 144/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 145/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 146/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 147/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 148/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 149/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 150/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 151/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 152/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 153/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 154/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 155/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 156/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 157/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 158/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 159/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 160/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 161/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 162/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 163/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 164/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 165/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 166/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 167/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 168/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 169/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 170/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 171/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 172/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 173/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 174/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 175/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 176/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 177/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 178/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 179/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 180/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 181/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 182/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 183/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 184/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 185/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 186/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 187/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 188/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 189/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 190/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 191/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 192/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 193/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 194/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 195/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 196/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 197/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 198/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 199/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 200/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 201/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 202/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 203/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 204/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 205/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 206/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 207/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 208/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 209/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 210/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 211/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 212/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 213/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 214/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 215/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 216/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 217/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 218/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 219/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 220/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 221/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 222/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 223/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 224/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 225/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 226/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 227/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 228/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 229/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 230/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 231/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 232/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 233/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 234/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 235/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 236/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 237/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 238/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 239/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 240/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 241/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 242/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 243/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 244/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 245/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 246/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 247/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 248/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 249/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 250/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 251/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 252/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 253/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 254/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 255/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 256/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 257/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 258/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 259/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 260/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 261/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 262/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 263/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 264/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 265/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 266/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 267/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 268/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 269/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 270/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 271/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 272/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 273/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 274/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 275/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 276/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 277/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 278/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 279/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 280/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 281/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 282/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 283/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 284/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 285/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 286/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 287/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 288/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 289/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 290/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 291/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 292/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 293/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 294/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 295/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 296/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 297/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 298/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 299/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 300/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 301/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 302/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 303/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 304/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 305/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 306/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 307/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 308/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 309/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 310/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 311/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 312/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 313/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 314/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 315/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 316/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 317/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 318/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 319/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 320/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 321/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 322/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 323/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 324/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 325/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 326/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 327/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 328/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 329/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 330/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 331/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 332/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 333/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 334/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 335/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 336/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 337/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 338/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 339/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 340/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 341/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 342/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 343/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 344/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 345/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 346/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 347/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 348/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 349/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 350/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 351/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 352/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 353/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 354/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 355/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 356/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 357/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 358/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 359/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 360/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 361/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 362/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 363/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 364/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 365/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 366/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 367/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 368/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 369/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 370/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 371/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 372/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 373/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 374/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 375/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 376/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 377/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 378/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 379/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 380/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 381/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 382/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 383/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 384/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 385/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 386/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 387/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 388/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 389/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 390/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 391/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 392/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 393/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 394/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 395/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 396/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 397/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 398/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 399/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 400/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 401/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 402/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 403/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 404/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 405/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 406/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 407/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 408/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 409/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 410/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 411/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 412/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 413/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 414/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 415/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 416/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 417/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 418/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 419/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 420/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 421/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 422/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 423/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 424/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 425/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 426/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 427/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 428/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 429/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 430/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 431/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 432/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 433/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 434/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 435/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 436/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 437/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 438/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 439/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 440/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 441/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 442/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 443/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 444/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 445/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 446/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 447/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 448/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 449/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 450/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 451/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 452/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 453/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 454/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 455/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 456/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 457/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 458/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 459/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 460/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 461/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 462/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 463/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 464/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 465/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 466/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 467/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 468/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 469/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 470/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 471/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 472/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 473/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 474/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 475/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 476/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 477/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 478/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 479/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 480/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 481/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 482/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 483/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 484/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 485/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 486/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 487/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 488/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 489/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 490/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 491/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 492/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 493/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 494/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 495/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 496/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 497/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 498/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 499/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 500/500:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/ECTRM/YahooAnswer_ECRTM_K20_seed42.mat

YahooAnswer | K=50 | seed=42:   0%|          | 0/500 [00:00<?, ?it/s]

epoch 1/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 2/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 3/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 4/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 5/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 6/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 7/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 8/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 9/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 10/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 11/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 12/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 13/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 14/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 15/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 16/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 17/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 18/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 19/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 20/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 21/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 22/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 23/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 24/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 25/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 26/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 27/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 28/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 29/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 30/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 31/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 32/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 33/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 34/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 35/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 36/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 37/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 38/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 39/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 40/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 41/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 42/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 43/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 44/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 45/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 46/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 47/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 48/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 49/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 50/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 51/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 52/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 53/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 54/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 55/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 56/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 57/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 58/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 59/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 60/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 61/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 62/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 63/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 64/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 65/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 66/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 67/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 68/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 69/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 70/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 71/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 72/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 73/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 74/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 75/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 76/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 77/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 78/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 79/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 80/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 81/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 82/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 83/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 84/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 85/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 86/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 87/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 88/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 89/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 90/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 91/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 92/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 93/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 94/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 95/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 96/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 97/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 98/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 99/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 100/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 101/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 102/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 103/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 104/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 105/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 106/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 107/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 108/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 109/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 110/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 111/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 112/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 113/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 114/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 115/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 116/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 117/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 118/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 119/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 120/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 121/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 122/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 123/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 124/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 125/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 126/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 127/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 128/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 129/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 130/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 131/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 132/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 133/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 134/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 135/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 136/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 137/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 138/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 139/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 140/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 141/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 142/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 143/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 144/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 145/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 146/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 147/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 148/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 149/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 150/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 151/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 152/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 153/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 154/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 155/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 156/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 157/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 158/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 159/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 160/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 161/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 162/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 163/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 164/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 165/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 166/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 167/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 168/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 169/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 170/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 171/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 172/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 173/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 174/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 175/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 176/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 177/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 178/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 179/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 180/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 181/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 182/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 183/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 184/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 185/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 186/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 187/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 188/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 189/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 190/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 191/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 192/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 193/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 194/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 195/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 196/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 197/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 198/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 199/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 200/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 201/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 202/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 203/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 204/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 205/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 206/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 207/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 208/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 209/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 210/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 211/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 212/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 213/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 214/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 215/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 216/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 217/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 218/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 219/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 220/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 221/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 222/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 223/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 224/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 225/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 226/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 227/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 228/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 229/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 230/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 231/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 232/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 233/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 234/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 235/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 236/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 237/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 238/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 239/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 240/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 241/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 242/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 243/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 244/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 245/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 246/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 247/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 248/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 249/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 250/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 251/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 252/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 253/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 254/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 255/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 256/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 257/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 258/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 259/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 260/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 261/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 262/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 263/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 264/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 265/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 266/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 267/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 268/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 269/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 270/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 271/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 272/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 273/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 274/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 275/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 276/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 277/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 278/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 279/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 280/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 281/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 282/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 283/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 284/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 285/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 286/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 287/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 288/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 289/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 290/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 291/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 292/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 293/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 294/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 295/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 296/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 297/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 298/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 299/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 300/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 301/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 302/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 303/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 304/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 305/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 306/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 307/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 308/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 309/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 310/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 311/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 312/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 313/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 314/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 315/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 316/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 317/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 318/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 319/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 320/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 321/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 322/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 323/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 324/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 325/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 326/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 327/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 328/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 329/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 330/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 331/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 332/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 333/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 334/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 335/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 336/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 337/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 338/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 339/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 340/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 341/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 342/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 343/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 344/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 345/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 346/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 347/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 348/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 349/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 350/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 351/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 352/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 353/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 354/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 355/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 356/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 357/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 358/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 359/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 360/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 361/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 362/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 363/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 364/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 365/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 366/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 367/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 368/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 369/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 370/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 371/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 372/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 373/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 374/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 375/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 376/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 377/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 378/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 379/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 380/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 381/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 382/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 383/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 384/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 385/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 386/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 387/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 388/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 389/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 390/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 391/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 392/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 393/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 394/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 395/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 396/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 397/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 398/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 399/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 400/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 401/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 402/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 403/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 404/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 405/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 406/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 407/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 408/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 409/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 410/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 411/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 412/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 413/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 414/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 415/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 416/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 417/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 418/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 419/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 420/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 421/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 422/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 423/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 424/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 425/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 426/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 427/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 428/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 429/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 430/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 431/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 432/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 433/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 434/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 435/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 436/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 437/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 438/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 439/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 440/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 441/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 442/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 443/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 444/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 445/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 446/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 447/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 448/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 449/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 450/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 451/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 452/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 453/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 454/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 455/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 456/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 457/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 458/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 459/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 460/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 461/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 462/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 463/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 464/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 465/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 466/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 467/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 468/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 469/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 470/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 471/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 472/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 473/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 474/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 475/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 476/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 477/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 478/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 479/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 480/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 481/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 482/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 483/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 484/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 485/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 486/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 487/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 488/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 489/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 490/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 491/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 492/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 493/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 494/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 495/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 496/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 497/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 498/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 499/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 500/500:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/ECTRM/YahooAnswer_ECRTM_K50_seed42.mat

YahooAnswer | K=100 | seed=42:   0%|          | 0/500 [00:00<?, ?it/s]

epoch 1/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 2/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 3/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 4/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 5/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 6/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 7/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 8/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 9/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 10/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 11/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 12/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 13/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 14/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 15/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 16/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 17/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 18/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 19/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 20/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 21/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 22/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 23/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 24/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 25/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 26/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 27/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 28/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 29/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 30/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 31/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 32/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 33/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 34/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 35/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 36/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 37/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 38/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 39/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 40/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 41/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 42/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 43/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 44/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 45/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 46/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 47/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 48/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 49/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 50/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 51/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 52/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 53/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 54/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 55/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 56/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 57/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 58/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 59/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 60/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 61/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 62/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 63/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 64/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 65/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 66/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 67/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 68/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 69/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 70/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 71/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 72/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 73/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 74/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 75/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 76/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 77/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 78/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 79/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 80/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 81/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 82/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 83/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 84/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 85/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 86/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 87/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 88/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 89/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 90/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 91/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 92/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 93/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 94/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 95/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 96/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 97/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 98/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 99/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 100/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 101/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 102/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 103/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 104/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 105/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 106/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 107/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 108/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 109/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 110/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 111/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 112/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 113/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 114/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 115/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 116/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 117/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 118/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 119/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 120/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 121/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 122/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 123/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 124/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 125/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 126/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 127/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 128/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 129/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 130/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 131/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 132/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 133/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 134/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 135/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 136/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 137/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 138/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 139/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 140/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 141/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 142/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 143/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 144/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 145/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 146/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 147/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 148/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 149/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 150/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 151/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 152/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 153/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 154/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 155/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 156/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 157/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 158/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 159/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 160/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 161/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 162/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 163/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 164/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 165/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 166/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 167/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 168/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 169/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 170/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 171/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 172/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 173/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 174/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 175/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 176/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 177/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 178/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 179/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 180/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 181/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 182/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 183/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 184/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 185/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 186/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 187/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 188/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 189/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 190/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 191/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 192/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 193/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 194/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 195/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 196/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 197/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 198/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 199/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 200/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 201/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 202/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 203/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 204/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 205/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 206/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 207/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 208/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 209/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 210/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 211/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 212/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 213/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 214/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 215/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 216/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 217/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 218/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 219/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 220/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 221/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 222/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 223/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 224/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 225/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 226/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 227/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 228/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 229/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 230/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 231/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 232/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 233/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 234/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 235/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 236/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 237/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 238/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 239/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 240/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 241/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 242/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 243/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 244/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 245/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 246/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 247/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 248/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 249/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 250/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 251/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 252/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 253/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 254/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 255/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 256/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 257/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 258/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 259/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 260/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 261/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 262/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 263/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 264/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 265/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 266/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 267/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 268/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 269/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 270/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 271/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 272/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 273/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 274/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 275/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 276/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 277/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 278/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 279/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 280/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 281/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 282/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 283/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 284/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 285/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 286/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 287/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 288/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 289/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 290/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 291/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 292/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 293/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 294/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 295/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 296/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 297/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 298/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 299/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 300/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 301/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 302/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 303/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 304/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 305/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 306/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 307/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 308/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 309/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 310/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 311/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 312/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 313/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 314/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 315/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 316/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 317/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 318/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 319/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 320/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 321/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 322/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 323/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 324/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 325/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 326/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 327/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 328/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 329/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 330/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 331/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 332/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 333/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 334/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 335/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 336/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 337/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 338/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 339/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 340/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 341/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 342/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 343/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 344/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 345/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 346/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 347/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 348/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 349/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 350/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 351/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 352/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 353/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 354/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 355/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 356/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 357/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 358/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 359/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 360/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 361/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 362/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 363/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 364/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 365/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 366/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 367/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 368/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 369/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 370/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 371/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 372/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 373/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 374/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 375/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 376/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 377/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 378/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 379/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 380/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 381/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 382/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 383/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 384/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 385/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 386/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 387/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 388/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 389/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 390/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 391/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 392/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 393/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 394/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 395/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 396/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 397/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 398/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 399/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 400/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 401/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 402/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 403/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 404/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 405/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 406/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 407/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 408/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 409/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 410/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 411/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 412/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 413/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 414/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 415/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 416/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 417/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 418/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 419/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 420/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 421/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 422/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 423/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 424/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 425/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 426/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 427/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 428/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 429/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 430/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 431/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 432/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 433/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 434/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 435/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 436/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 437/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 438/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 439/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 440/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 441/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 442/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 443/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 444/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 445/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 446/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 447/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 448/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 449/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 450/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 451/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 452/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 453/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 454/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 455/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 456/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 457/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 458/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 459/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 460/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 461/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 462/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 463/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 464/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 465/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 466/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 467/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 468/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 469/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 470/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 471/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 472/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 473/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 474/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 475/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 476/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 477/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 478/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 479/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 480/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 481/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 482/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 483/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 484/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 485/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 486/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 487/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 488/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 489/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 490/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 491/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 492/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 493/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 494/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 495/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 496/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 497/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 498/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 499/500:   0%|          | 0/50 [00:00<?, ?it/s]

epoch 500/500:   0%|          | 0/50 [00:00<?, ?it/s]

Saved: /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/ECTRM/YahooAnswer_ECRTM_K100_seed42.mat

 Imports + dossier de sortie LDA

In [10]:
import os
import numpy as np
import scipy.io
import scipy.sparse as sp
from sklearn.decomposition import LatentDirichletAllocation

RUNS_DIR = "/Users/hydersidra/Documents/Master/PPD/ECRTM_runs"  
os.makedirs(RUNS_DIR, exist_ok=True)
print("RUNS_DIR =", RUNS_DIR)

OUT_DIR_LDA = os.path.join(RUNS_DIR, "LDA")
os.makedirs(OUT_DIR_LDA, exist_ok=True)
print("OUT_DIR_LDA =", OUT_DIR_LDA)

/Users/hydersidra/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py:1214: RuntimeWarning:
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

RUNS_DIR = /Users/hydersidra/Documents/Master/PPD/ECRTM_runs
OUT_DIR_LDA = /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/LDA

Loader sparse (spécifique LDA)

In [11]:
def load_bow_sparse(path):
    return sp.load_npz(path)

Elle prend un chemin de fichier en entrée (path) ensuite elle renvoie la matrice sparse SciPy telle qu’elle a 
été sauvegardée

Fonction train_one_lda(dataset, K)

In [13]:
def train_one_lda(dataset, K, seed=42, max_iter=50):
    data_dir = os.path.join(DATA_ROOT, dataset)

    X_train = load_bow_sparse(os.path.join(data_dir, "train_bow.npz"))
    X_test  = load_bow_sparse(os.path.join(data_dir, "test_bow.npz"))

    out_path = os.path.join(OUT_DIR_LDA, f"{dataset}_LDA_K{K}_seed{seed}.mat")
    if os.path.exists(out_path):
        print("Skip (already exists):", out_path)
        return out_path

    lda = LatentDirichletAllocation(
        n_components=K,           
        max_iter=max_iter,        
        learning_method="batch",
        random_state=seed,
        verbose=1                 
    )
    lda.fit(X_train) 

    beta = lda.components_.astype(np.float32)          
    beta = beta / beta.sum(axis=1, keepdims=True)

    train_theta = lda.transform(X_train).astype(np.float32)  
    test_theta  = lda.transform(X_test).astype(np.float32)   

    scipy.io.savemat(out_path, {"beta": beta, "train_theta": train_theta, "test_theta": test_theta})
    print("Saved:", out_path)
    return out_path

- Elle lit les BoW train et test.
- Elle entraîne LDA avec K topics.
- Elle calcule les topics–mots (beta) et les doc–topics (theta pour train et test).
- Elle enregistre tout ça dans un fichier .mat et renvoie son chemin

20NG

In [25]:
for K in [20, 50, 100]:
    train_one_lda("20NG", K=K, seed=42, max_iter=50)

Skip (already exists): /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/LDA/20NG_LDA_K20_seed42.mat
Skip (already exists): /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/LDA/20NG_LDA_K50_seed42.mat
Skip (already exists): /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/LDA/20NG_LDA_K100_seed42.mat

AGNews

In [ ]:
for K in [20, 50, 100]:
    train_one_lda("AGNews", K=K, seed=42, max_iter=50)

YahooAnswer

In [14]:
for K in [20, 50, 100]:
    train_one_lda("YahooAnswer", K=K, seed=42, max_iter=50)

iteration: 1 of max_iter: 50
iteration: 2 of max_iter: 50
iteration: 3 of max_iter: 50
iteration: 4 of max_iter: 50
iteration: 5 of max_iter: 50
iteration: 6 of max_iter: 50
iteration: 7 of max_iter: 50
iteration: 8 of max_iter: 50
iteration: 9 of max_iter: 50
iteration: 10 of max_iter: 50
iteration: 11 of max_iter: 50
iteration: 12 of max_iter: 50
iteration: 13 of max_iter: 50
iteration: 14 of max_iter: 50
iteration: 15 of max_iter: 50
iteration: 16 of max_iter: 50
iteration: 17 of max_iter: 50
iteration: 18 of max_iter: 50
iteration: 19 of max_iter: 50
iteration: 20 of max_iter: 50
iteration: 21 of max_iter: 50
iteration: 22 of max_iter: 50
iteration: 23 of max_iter: 50
iteration: 24 of max_iter: 50
iteration: 25 of max_iter: 50
iteration: 26 of max_iter: 50
iteration: 27 of max_iter: 50
iteration: 28 of max_iter: 50
iteration: 29 of max_iter: 50
iteration: 30 of max_iter: 50
iteration: 31 of max_iter: 50
iteration: 32 of max_iter: 50
iteration: 33 of max_iter: 50
iteration: 34 of max_iter: 50
iteration: 35 of max_iter: 50
iteration: 36 of max_iter: 50
iteration: 37 of max_iter: 50
iteration: 38 of max_iter: 50
iteration: 39 of max_iter: 50
iteration: 40 of max_iter: 50
iteration: 41 of max_iter: 50
iteration: 42 of max_iter: 50
iteration: 43 of max_iter: 50
iteration: 44 of max_iter: 50
iteration: 45 of max_iter: 50
iteration: 46 of max_iter: 50
iteration: 47 of max_iter: 50
iteration: 48 of max_iter: 50
iteration: 49 of max_iter: 50
iteration: 50 of max_iter: 50
Saved: /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/LDA/YahooAnswer_LDA_K20_seed42.mat
iteration: 1 of max_iter: 50
iteration: 2 of max_iter: 50
iteration: 3 of max_iter: 50
iteration: 4 of max_iter: 50
iteration: 5 of max_iter: 50
iteration: 6 of max_iter: 50
iteration: 7 of max_iter: 50
iteration: 8 of max_iter: 50
iteration: 9 of max_iter: 50
iteration: 10 of max_iter: 50
iteration: 11 of max_iter: 50
iteration: 12 of max_iter: 50
iteration: 13 of max_iter: 50
iteration: 14 of max_iter: 50
iteration: 15 of max_iter: 50
iteration: 16 of max_iter: 50
iteration: 17 of max_iter: 50
iteration: 18 of max_iter: 50
iteration: 19 of max_iter: 50
iteration: 20 of max_iter: 50
iteration: 21 of max_iter: 50
iteration: 22 of max_iter: 50
iteration: 23 of max_iter: 50
iteration: 24 of max_iter: 50
iteration: 25 of max_iter: 50
iteration: 26 of max_iter: 50
iteration: 27 of max_iter: 50
iteration: 28 of max_iter: 50
iteration: 29 of max_iter: 50
iteration: 30 of max_iter: 50
iteration: 31 of max_iter: 50
iteration: 32 of max_iter: 50
iteration: 33 of max_iter: 50
iteration: 34 of max_iter: 50
iteration: 35 of max_iter: 50
iteration: 36 of max_iter: 50
iteration: 37 of max_iter: 50
iteration: 38 of max_iter: 50
iteration: 39 of max_iter: 50
iteration: 40 of max_iter: 50
iteration: 41 of max_iter: 50
iteration: 42 of max_iter: 50
iteration: 43 of max_iter: 50
iteration: 44 of max_iter: 50
iteration: 45 of max_iter: 50
iteration: 46 of max_iter: 50
iteration: 47 of max_iter: 50
iteration: 48 of max_iter: 50
iteration: 49 of max_iter: 50
iteration: 50 of max_iter: 50
Saved: /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/LDA/YahooAnswer_LDA_K50_seed42.mat
iteration: 1 of max_iter: 50
iteration: 2 of max_iter: 50
iteration: 3 of max_iter: 50
iteration: 4 of max_iter: 50
iteration: 5 of max_iter: 50
iteration: 6 of max_iter: 50
iteration: 7 of max_iter: 50
iteration: 8 of max_iter: 50
iteration: 9 of max_iter: 50
iteration: 10 of max_iter: 50
iteration: 11 of max_iter: 50
iteration: 12 of max_iter: 50
iteration: 13 of max_iter: 50
iteration: 14 of max_iter: 50
iteration: 15 of max_iter: 50
iteration: 16 of max_iter: 50
iteration: 17 of max_iter: 50
iteration: 18 of max_iter: 50
iteration: 19 of max_iter: 50
iteration: 20 of max_iter: 50
iteration: 21 of max_iter: 50
iteration: 22 of max_iter: 50
iteration: 23 of max_iter: 50
iteration: 24 of max_iter: 50
iteration: 25 of max_iter: 50
iteration: 26 of max_iter: 50
iteration: 27 of max_iter: 50
iteration: 28 of max_iter: 50
iteration: 29 of max_iter: 50
iteration: 30 of max_iter: 50
iteration: 31 of max_iter: 50
iteration: 32 of max_iter: 50
iteration: 33 of max_iter: 50
iteration: 34 of max_iter: 50
iteration: 35 of max_iter: 50
iteration: 36 of max_iter: 50
iteration: 37 of max_iter: 50
iteration: 38 of max_iter: 50
iteration: 39 of max_iter: 50
iteration: 40 of max_iter: 50
iteration: 41 of max_iter: 50
iteration: 42 of max_iter: 50
iteration: 43 of max_iter: 50
iteration: 44 of max_iter: 50
iteration: 45 of max_iter: 50
iteration: 46 of max_iter: 50
iteration: 47 of max_iter: 50
iteration: 48 of max_iter: 50
iteration: 49 of max_iter: 50
iteration: 50 of max_iter: 50
Saved: /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/LDA/YahooAnswer_LDA_K100_seed42.mat

In [33]:
for K in [20, 50, 100]:
    train_one_lda("YahooAnswer", K=K, seed=42, max_iter=200)

iteration: 1 of max_iter: 200
iteration: 2 of max_iter: 200
iteration: 3 of max_iter: 200
iteration: 4 of max_iter: 200
iteration: 5 of max_iter: 200
iteration: 6 of max_iter: 200
iteration: 7 of max_iter: 200
iteration: 8 of max_iter: 200
iteration: 9 of max_iter: 200
iteration: 10 of max_iter: 200
iteration: 11 of max_iter: 200
iteration: 12 of max_iter: 200
iteration: 13 of max_iter: 200
iteration: 14 of max_iter: 200
iteration: 15 of max_iter: 200
iteration: 16 of max_iter: 200
iteration: 17 of max_iter: 200
iteration: 18 of max_iter: 200
iteration: 19 of max_iter: 200
iteration: 20 of max_iter: 200
iteration: 21 of max_iter: 200
iteration: 22 of max_iter: 200
iteration: 23 of max_iter: 200
iteration: 24 of max_iter: 200
iteration: 25 of max_iter: 200
iteration: 26 of max_iter: 200
iteration: 27 of max_iter: 200
iteration: 28 of max_iter: 200
iteration: 29 of max_iter: 200
iteration: 30 of max_iter: 200
iteration: 31 of max_iter: 200
iteration: 32 of max_iter: 200
iteration: 33 of max_iter: 200
iteration: 34 of max_iter: 200
iteration: 35 of max_iter: 200
iteration: 36 of max_iter: 200
iteration: 37 of max_iter: 200
iteration: 38 of max_iter: 200
iteration: 39 of max_iter: 200
iteration: 40 of max_iter: 200
iteration: 41 of max_iter: 200
iteration: 42 of max_iter: 200
iteration: 43 of max_iter: 200
iteration: 44 of max_iter: 200
iteration: 45 of max_iter: 200
iteration: 46 of max_iter: 200
iteration: 47 of max_iter: 200
iteration: 48 of max_iter: 200
iteration: 49 of max_iter: 200
iteration: 50 of max_iter: 200
iteration: 51 of max_iter: 200
iteration: 52 of max_iter: 200
iteration: 53 of max_iter: 200
iteration: 54 of max_iter: 200
iteration: 55 of max_iter: 200
iteration: 56 of max_iter: 200
iteration: 57 of max_iter: 200
iteration: 58 of max_iter: 200
iteration: 59 of max_iter: 200
iteration: 60 of max_iter: 200
iteration: 61 of max_iter: 200
iteration: 62 of max_iter: 200
iteration: 63 of max_iter: 200
iteration: 64 of max_iter: 200
iteration: 65 of max_iter: 200
iteration: 66 of max_iter: 200
iteration: 67 of max_iter: 200
iteration: 68 of max_iter: 200
iteration: 69 of max_iter: 200
iteration: 70 of max_iter: 200
iteration: 71 of max_iter: 200
iteration: 72 of max_iter: 200
iteration: 73 of max_iter: 200
iteration: 74 of max_iter: 200
iteration: 75 of max_iter: 200
iteration: 76 of max_iter: 200
iteration: 77 of max_iter: 200
iteration: 78 of max_iter: 200
iteration: 79 of max_iter: 200
iteration: 80 of max_iter: 200
iteration: 81 of max_iter: 200
iteration: 82 of max_iter: 200
iteration: 83 of max_iter: 200
iteration: 84 of max_iter: 200
iteration: 85 of max_iter: 200
iteration: 86 of max_iter: 200
iteration: 87 of max_iter: 200
iteration: 88 of max_iter: 200
iteration: 89 of max_iter: 200
iteration: 90 of max_iter: 200
iteration: 91 of max_iter: 200
iteration: 92 of max_iter: 200
iteration: 93 of max_iter: 200
iteration: 94 of max_iter: 200
iteration: 95 of max_iter: 200
iteration: 96 of max_iter: 200
iteration: 97 of max_iter: 200
iteration: 98 of max_iter: 200
iteration: 99 of max_iter: 200
iteration: 100 of max_iter: 200
iteration: 101 of max_iter: 200
iteration: 102 of max_iter: 200
iteration: 103 of max_iter: 200
iteration: 104 of max_iter: 200
iteration: 105 of max_iter: 200
iteration: 106 of max_iter: 200
iteration: 107 of max_iter: 200
iteration: 108 of max_iter: 200
iteration: 109 of max_iter: 200
iteration: 110 of max_iter: 200
iteration: 111 of max_iter: 200
iteration: 112 of max_iter: 200
iteration: 113 of max_iter: 200
iteration: 114 of max_iter: 200
iteration: 115 of max_iter: 200
iteration: 116 of max_iter: 200
iteration: 117 of max_iter: 200
iteration: 118 of max_iter: 200
iteration: 119 of max_iter: 200
iteration: 120 of max_iter: 200
iteration: 121 of max_iter: 200
iteration: 122 of max_iter: 200
iteration: 123 of max_iter: 200
iteration: 124 of max_iter: 200
iteration: 125 of max_iter: 200
iteration: 126 of max_iter: 200
iteration: 127 of max_iter: 200
iteration: 128 of max_iter: 200
iteration: 129 of max_iter: 200
iteration: 130 of max_iter: 200
iteration: 131 of max_iter: 200
iteration: 132 of max_iter: 200
iteration: 133 of max_iter: 200
iteration: 134 of max_iter: 200
iteration: 135 of max_iter: 200
iteration: 136 of max_iter: 200
iteration: 137 of max_iter: 200
iteration: 138 of max_iter: 200
iteration: 139 of max_iter: 200
iteration: 140 of max_iter: 200
iteration: 141 of max_iter: 200
iteration: 142 of max_iter: 200
iteration: 143 of max_iter: 200
iteration: 144 of max_iter: 200
iteration: 145 of max_iter: 200
iteration: 146 of max_iter: 200
iteration: 147 of max_iter: 200
iteration: 148 of max_iter: 200
iteration: 149 of max_iter: 200
iteration: 150 of max_iter: 200
iteration: 151 of max_iter: 200
iteration: 152 of max_iter: 200
iteration: 153 of max_iter: 200
iteration: 154 of max_iter: 200
iteration: 155 of max_iter: 200
iteration: 156 of max_iter: 200
iteration: 157 of max_iter: 200
iteration: 158 of max_iter: 200
iteration: 159 of max_iter: 200
iteration: 160 of max_iter: 200
iteration: 161 of max_iter: 200
iteration: 162 of max_iter: 200
iteration: 163 of max_iter: 200
iteration: 164 of max_iter: 200
iteration: 165 of max_iter: 200
iteration: 166 of max_iter: 200
iteration: 167 of max_iter: 200
iteration: 168 of max_iter: 200
iteration: 169 of max_iter: 200
iteration: 170 of max_iter: 200
iteration: 171 of max_iter: 200
iteration: 172 of max_iter: 200
iteration: 173 of max_iter: 200
iteration: 174 of max_iter: 200
iteration: 175 of max_iter: 200
iteration: 176 of max_iter: 200
iteration: 177 of max_iter: 200
iteration: 178 of max_iter: 200
iteration: 179 of max_iter: 200
iteration: 180 of max_iter: 200
iteration: 181 of max_iter: 200
iteration: 182 of max_iter: 200
iteration: 183 of max_iter: 200
iteration: 184 of max_iter: 200
iteration: 185 of max_iter: 200
iteration: 186 of max_iter: 200
iteration: 187 of max_iter: 200
iteration: 188 of max_iter: 200
iteration: 189 of max_iter: 200
iteration: 190 of max_iter: 200
iteration: 191 of max_iter: 200
iteration: 192 of max_iter: 200
iteration: 193 of max_iter: 200
iteration: 194 of max_iter: 200
iteration: 195 of max_iter: 200
iteration: 196 of max_iter: 200
iteration: 197 of max_iter: 200
iteration: 198 of max_iter: 200
iteration: 199 of max_iter: 200
iteration: 200 of max_iter: 200
Saved: /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/LDA/YahooAnswer_LDA_K20_seed42.mat
iteration: 1 of max_iter: 200
iteration: 2 of max_iter: 200
iteration: 3 of max_iter: 200
iteration: 4 of max_iter: 200
iteration: 5 of max_iter: 200
iteration: 6 of max_iter: 200
iteration: 7 of max_iter: 200
iteration: 8 of max_iter: 200
iteration: 9 of max_iter: 200
iteration: 10 of max_iter: 200
iteration: 11 of max_iter: 200
iteration: 12 of max_iter: 200
iteration: 13 of max_iter: 200
iteration: 14 of max_iter: 200
iteration: 15 of max_iter: 200
iteration: 16 of max_iter: 200
iteration: 17 of max_iter: 200
iteration: 18 of max_iter: 200
iteration: 19 of max_iter: 200
iteration: 20 of max_iter: 200
iteration: 21 of max_iter: 200

KeyboardInterrupt:

In [39]:
import os
import numpy as np
import scipy.io 

# CHEMINS
PROJECT_DIR = "/Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM"
OUT_DIR = "/Users/hydersidra/Documents/Master/PPD/ECRTM_runs"
OUT_DIR_LDA = f"{OUT_DIR}/LDA"

DATASET = "YahooAnswer"  
VOCAB_PATH = os.path.join(PROJECT_DIR, f"data/{DATASET}/vocab.txt")

METRICS_DIR = os.path.join(PROJECT_DIR, "metrics")
os.makedirs(METRICS_DIR, exist_ok=True)

# Chargé VOCABULAIRE
with open(VOCAB_PATH, "r", encoding="utf-8") as f:
    vocab = [line.strip() for line in f if line.strip()]

print(f" Vocab chargé : {len(vocab)} mots")

# Configuration
TOPN = 15  
configs = [
    ("LDA", 20, 42),
    ("LDA", 50, 42),
    ("LDA", 100, 42),
]

# generer les topics files 
for model, K, seed in configs:
    # Charger le .mat
    mat_file = f"{DATASET}_{model}_K{K}_seed{seed}.mat"
    mat_path = os.path.join(OUT_DIR_LDA, mat_file)
    
    if not os.path.isfile(mat_path):
        print(f"MANQUANT: {mat_path}")
        continue
    
    loaded_data = scipy.io.loadmat(mat_path)
    beta = loaded_data["beta"]  # (K, V)
    
    # Générer le fichier topics
    topics_file = os.path.join(METRICS_DIR, f"topics_{DATASET}_{model}_K{K}_seed{seed}.txt")
    
    with open(topics_file, "w", encoding="utf-8") as f:
        for k in range(beta.shape[0]):
            top_idx = np.argsort(beta[k])[::-1][:TOPN]
            f.write(" ".join(vocab[i] for i in top_idx) + "\n")  # ← FIX: \n pas \\n
    
    print(f"Topics sauvegardés : {topics_file}")

print("\n Terminé !")

 Vocab chargé : 5000 mots
Topics sauvegardés : /Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM/metrics/topics_YahooAnswer_LDA_K20_seed42.txt
Topics sauvegardés : /Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM/metrics/topics_YahooAnswer_LDA_K50_seed42.txt
Topics sauvegardés : /Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM/metrics/topics_YahooAnswer_LDA_K100_seed42.txt

 Terminé !

PALMETTO

In [16]:
WIKI_DIR="/Users/hydersidra/Documents/Master/PPD/ECRTM_project/palmetto/Wikipedia_bd"
!mkdir -p "$WIKI_DIR"

!ls -l "$WIKI_DIR/wikipedia_bd"

total 13422928
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3f5.cfe
-rw-r--r--@ 1 hydersidra  staff    10708619 21 mai  2014 _3f5.cfs
-rw-r--r--@ 1 hydersidra  staff         285 21 mai  2014 _3f5.si
-rw-r--r--@ 1 hydersidra  staff   928213930 21 mai  2014 _3gj_Lucene41_0.doc
-rw-r--r--@ 1 hydersidra  staff  1464777604 21 mai  2014 _3gj_Lucene41_0.pos
-rw-r--r--@ 1 hydersidra  staff   154487950 21 mai  2014 _3gj_Lucene41_0.tim
-rw-r--r--@ 1 hydersidra  staff     3327506 21 mai  2014 _3gj_Lucene41_0.tip
-rw-r--r--@ 1 hydersidra  staff    11999360 21 mai  2014 _3gj.fdt
-rw-r--r--@ 1 hydersidra  staff       41205 21 mai  2014 _3gj.fdx
-rw-r--r--@ 1 hydersidra  staff         125 21 mai  2014 _3gj.fnm
-rw-r--r--@ 1 hydersidra  staff     3069026 21 mai  2014 _3gj.nvd
-rw-r--r--@ 1 hydersidra  staff          46 21 mai  2014 _3gj.nvm
-rw-r--r--@ 1 hydersidra  staff         409 21 mai  2014 _3gj.si
-rw-r--r--@ 1 hydersidra  staff  2746741666 21 mai  2014 _3gj.tvd
-rw-r--r--@ 1 hydersidra  staff     1525952 21 mai  2014 _3gj.tvx
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3gt.cfe
-rw-r--r--@ 1 hydersidra  staff     7716838 21 mai  2014 _3gt.cfs
-rw-r--r--@ 1 hydersidra  staff         285 21 mai  2014 _3gt.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3ir.cfe
-rw-r--r--@ 1 hydersidra  staff    10085074 21 mai  2014 _3ir.cfs
-rw-r--r--@ 1 hydersidra  staff         285 21 mai  2014 _3ir.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3j1.cfe
-rw-r--r--@ 1 hydersidra  staff    10131885 21 mai  2014 _3j1.cfs
-rw-r--r--@ 1 hydersidra  staff         285 21 mai  2014 _3j1.si
-rw-r--r--@ 1 hydersidra  staff   178787257 21 mai  2014 _3je_Lucene41_0.doc
-rw-r--r--@ 1 hydersidra  staff   255431726 21 mai  2014 _3je_Lucene41_0.pos
-rw-r--r--@ 1 hydersidra  staff    52257203 21 mai  2014 _3je_Lucene41_0.tim
-rw-r--r--@ 1 hydersidra  staff     1090387 21 mai  2014 _3je_Lucene41_0.tip
-rw-r--r--@ 1 hydersidra  staff     3324312 21 mai  2014 _3je.fdt
-rw-r--r--@ 1 hydersidra  staff       12846 21 mai  2014 _3je.fdx
-rw-r--r--@ 1 hydersidra  staff         125 21 mai  2014 _3je.fnm
-rw-r--r--@ 1 hydersidra  staff      883026 21 mai  2014 _3je.nvd
-rw-r--r--@ 1 hydersidra  staff          46 21 mai  2014 _3je.nvm
-rw-r--r--@ 1 hydersidra  staff         410 21 mai  2014 _3je.si
-rw-r--r--@ 1 hydersidra  staff   533035369 21 mai  2014 _3je.tvd
-rw-r--r--@ 1 hydersidra  staff      321225 21 mai  2014 _3je.tvx
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3jp.cfe
-rw-r--r--@ 1 hydersidra  staff    10359679 21 mai  2014 _3jp.cfs
-rw-r--r--@ 1 hydersidra  staff         285 21 mai  2014 _3jp.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3ks.cfe
-rw-r--r--@ 1 hydersidra  staff    10026884 21 mai  2014 _3ks.cfs
-rw-r--r--@ 1 hydersidra  staff         285 21 mai  2014 _3ks.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3m7.cfe
-rw-r--r--@ 1 hydersidra  staff   107017285 21 mai  2014 _3m7.cfs
-rw-r--r--@ 1 hydersidra  staff         285 21 mai  2014 _3m7.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3m8.cfe
-rw-r--r--@ 1 hydersidra  staff     1527308 21 mai  2014 _3m8.cfs
-rw-r--r--@ 1 hydersidra  staff         247 21 mai  2014 _3m8.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3mb.cfe
-rw-r--r--@ 1 hydersidra  staff     1431932 21 mai  2014 _3mb.cfs
-rw-r--r--@ 1 hydersidra  staff         247 21 mai  2014 _3mb.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3mh.cfe
-rw-r--r--@ 1 hydersidra  staff    10246373 21 mai  2014 _3mh.cfs
-rw-r--r--@ 1 hydersidra  staff         285 21 mai  2014 _3mh.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3mi.cfe
-rw-r--r--@ 1 hydersidra  staff     1495145 21 mai  2014 _3mi.cfs
-rw-r--r--@ 1 hydersidra  staff         247 21 mai  2014 _3mi.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3mj.cfe
-rw-r--r--@ 1 hydersidra  staff     1563441 21 mai  2014 _3mj.cfs
-rw-r--r--@ 1 hydersidra  staff         247 21 mai  2014 _3mj.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3mr.cfe
-rw-r--r--@ 1 hydersidra  staff    11353141 21 mai  2014 _3mr.cfs
-rw-r--r--@ 1 hydersidra  staff         285 21 mai  2014 _3mr.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3mv.cfe
-rw-r--r--@ 1 hydersidra  staff     1404812 21 mai  2014 _3mv.cfs
-rw-r--r--@ 1 hydersidra  staff         247 21 mai  2014 _3mv.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3n1.cfe
-rw-r--r--@ 1 hydersidra  staff    10779848 21 mai  2014 _3n1.cfs
-rw-r--r--@ 1 hydersidra  staff         285 21 mai  2014 _3n1.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3nb.cfe
-rw-r--r--@ 1 hydersidra  staff    10761348 21 mai  2014 _3nb.cfs
-rw-r--r--@ 1 hydersidra  staff         285 21 mai  2014 _3nb.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3nc.cfe
-rw-r--r--@ 1 hydersidra  staff      931931 21 mai  2014 _3nc.cfs
-rw-r--r--@ 1 hydersidra  staff         247 21 mai  2014 _3nc.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3nd.cfe
-rw-r--r--@ 1 hydersidra  staff     1000130 21 mai  2014 _3nd.cfs
-rw-r--r--@ 1 hydersidra  staff         247 21 mai  2014 _3nd.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3ne.cfe
-rw-r--r--@ 1 hydersidra  staff     1174990 21 mai  2014 _3ne.cfs
-rw-r--r--@ 1 hydersidra  staff         247 21 mai  2014 _3ne.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3nf.cfe
-rw-r--r--@ 1 hydersidra  staff     1137025 21 mai  2014 _3nf.cfs
-rw-r--r--@ 1 hydersidra  staff         247 21 mai  2014 _3nf.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3ng.cfe
-rw-r--r--@ 1 hydersidra  staff     1106711 21 mai  2014 _3ng.cfs
-rw-r--r--@ 1 hydersidra  staff         247 21 mai  2014 _3ng.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3nh.cfe
-rw-r--r--@ 1 hydersidra  staff      985640 21 mai  2014 _3nh.cfs
-rw-r--r--@ 1 hydersidra  staff         247 21 mai  2014 _3nh.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3ni.cfe
-rw-r--r--@ 1 hydersidra  staff     1116180 21 mai  2014 _3ni.cfs
-rw-r--r--@ 1 hydersidra  staff         247 21 mai  2014 _3ni.si
-rw-r--r--@ 1 hydersidra  staff         310 21 mai  2014 _3nj.cfe
-rw-r--r--@ 1 hydersidra  staff      760886 21 mai  2014 _3nj.cfs
-rw-r--r--@ 1 hydersidra  staff         247 21 mai  2014 _3nj.si
-rw-r--r--@ 1 hydersidra  staff    47800979 21 mai  2014 _a4_Lucene41_0.doc
-rw-r--r--@ 1 hydersidra  staff    87921257 21 mai  2014 _a4_Lucene41_0.pos
-rw-r--r--@ 1 hydersidra  staff    18606977 21 mai  2014 _a4_Lucene41_0.tim
-rw-r--r--@ 1 hydersidra  staff      424689 21 mai  2014 _a4_Lucene41_0.tip
-rw-r--r--@ 1 hydersidra  staff      409477 21 mai  2014 _a4.fdt
-rw-r--r--@ 1 hydersidra  staff        1122 21 mai  2014 _a4.fdx
-rw-r--r--@ 1 hydersidra  staff         125 21 mai  2014 _a4.fnm
-rw-r--r--@ 1 hydersidra  staff      100026 21 mai  2014 _a4.nvd
-rw-r--r--@ 1 hydersidra  staff          46 21 mai  2014 _a4.nvm
-rw-r--r--@ 1 hydersidra  staff         398 21 mai  2014 _a4.si
-rw-r--r--@ 1 hydersidra  staff   152701797 21 mai  2014 _a4.tvd
-rw-r--r--@ 1 hydersidra  staff       76927 21 mai  2014 _a4.tvx
-rw-r--r--@ 1 hydersidra  staff         746 21 mai  2014 segments_3ah
-rw-r--r--@ 1 hydersidra  staff          20 21 mai  2014 segments.gen

In [17]:
!test -f "$PALMETTO_JAR" && echo "OK: jar" || echo "KO: jar"
!test -d "$WIKI_BD_DIR" && echo "OK: wikipedia_bd dir" || echo "KO: wikipedia_bd dir"
!test -f "$TOPICS_FILE" && echo "OK: topics file" || echo "KO: topics file"

!ls -lah "/Users/hydersidra/Documents/Master/PPD/ECRTM_project/palmetto/Wikipedia_bd" | head -n 50

KO: jar
KO: wikipedia_bd dir
OK: topics file
total 352
drwx------@   5 hydersidra  staff   160B 26 jan 11:15 .
drwxr-xr-x@   5 hydersidra  staff   160B 26 jan 11:15 ..
-rw-r--r--@   1 hydersidra  staff   8,0K 26 jan 11:16 .DS_Store
drwxr-xr-x@ 112 hydersidra  staff   3,5K 26 jan 11:15 wikipedia_bd
-rw-r--r--@   1 hydersidra  staff   162K 24 avr  2014 wikipedia_bd.histogram

In [35]:
import os
import numpy as np
import scipy.io
import subprocess

#  Chemins 
PROJECT_DIR = "/Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM"

DATASET = "YahooAnswer"
VOCAB_PATH = os.path.join(PROJECT_DIR, f"data/{DATASET}/vocab.txt")

OUT_DIR = "/Users/hydersidra/Documents/Master/PPD/ECRTM_runs"
OUT_DIR_LDA   = f"{OUT_DIR}/LDA"
OUT_DIR_ECRTM = f"{OUT_DIR}/ECRTM"

os.makedirs(OUT_DIR_LDA, exist_ok=True)
os.makedirs(OUT_DIR_ECRTM, exist_ok=True)

# Palmetto 
PALMETTO_JAR = "/Users/hydersidra/Documents/Master/PPD/ECRTM_project/palmetto/palmetto-0.1.0-jar-with-dependencies.jar"
WIKI_BD_DIR  = "/Users/hydersidra/Documents/Master/PPD/ECRTM_project/palmetto/Wikipedia_bd/wikipedia_bd"
TOPN = 15

# Vocab
with open(VOCAB_PATH, "r", encoding="utf-8") as f:
    vocab = [line.strip() for line in f if line.strip()]

print(f"Vocab chargé: {len(vocab)} mots\n")

# Fichiers .mat 
lda_files = [
    "YahooAnswer_LDA_K20_seed42.mat",
    "YahooAnswer_LDA_K50_seed42.mat",
    "YahooAnswer_LDA_K100_seed42.mat",
]

ecrtm_files = [
    "YahooAnswer_ECRTM_K20_seed42.mat",
    "YahooAnswer_ECRTM_K50_seed42.mat",
    "YahooAnswer_ECRTM_K100_seed42.mat",
]

#  Fonction de processing 
def process_mat_files(mat_files, base_dir, model_name):
    for mat_name in mat_files:
        mat_path = os.path.join(base_dir, mat_name)
        
        if not os.path.isfile(mat_path):
            print(f" Introuvable: {mat_path}")
            continue
        
        loaded = scipy.io.loadmat(mat_path)
        if "beta" not in loaded:
            print(f"'beta' introuvable dans {mat_name}. Keys: {list(loaded.keys())}")
            continue
        
        beta = loaded["beta"]  # (K, V)
        
        base_name = mat_name.replace(".mat", "")
        
        # Sauvegarde 
        topics_file = os.path.join(base_dir, f"topics_for_cv_{base_name}.txt")
        cv_out_file = os.path.join(base_dir, f"palmetto_CV_{base_name}.txt")
        
        # Écrire topics (top TOPN mots)
        with open(topics_file, "w", encoding="utf-8") as f:
            for k in range(beta.shape[0]):
                top_idx = np.argsort(beta[k])[::-1][:TOPN]
                # ← FIX ICI : \n au lieu de \\n
                f.write(" ".join(vocab[i] for i in top_idx) + "\n")
        
        # Lancer Palmetto
        cmd = ["java", "-jar", PALMETTO_JAR, WIKI_BD_DIR, "C_V", topics_file]
        try:
            out = subprocess.check_output(cmd, text=True, stderr=subprocess.STDOUT)
            with open(cv_out_file, "w", encoding="utf-8") as f:
                f.write(out)
            print(f"{model_name} OK: {mat_name} -> {cv_out_file}")
        except subprocess.CalledProcessError as e:
            print(f" Erreur Palmetto pour {mat_name}:\n{e.output}")


print("=== Processing LDA ===")
process_mat_files(lda_files, OUT_DIR_LDA, "LDA")

print("\n=== Processing ECRTM ===")
process_mat_files(ecrtm_files, OUT_DIR_ECRTM, "ECRTM")

print("\n Terminé. Résultats dans:")
print(f"  LDA   → {OUT_DIR_LDA}")
print(f"  ECRTM → {OUT_DIR_ECRTM}")

✅ Vocab chargé: 5000 mots

=== Processing LDA ===
✅ LDA OK: YahooAnswer_LDA_K20_seed42.mat -> /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/LDA/palmetto_CV_YahooAnswer_LDA_K20_seed42.txt
✅ LDA OK: YahooAnswer_LDA_K50_seed42.mat -> /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/LDA/palmetto_CV_YahooAnswer_LDA_K50_seed42.txt
✅ LDA OK: YahooAnswer_LDA_K100_seed42.mat -> /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/LDA/palmetto_CV_YahooAnswer_LDA_K100_seed42.txt

=== Processing ECRTM ===
✅ ECRTM OK: YahooAnswer_ECRTM_K20_seed42.mat -> /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/ECRTM/palmetto_CV_YahooAnswer_ECRTM_K20_seed42.txt
✅ ECRTM OK: YahooAnswer_ECRTM_K50_seed42.mat -> /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/ECRTM/palmetto_CV_YahooAnswer_ECRTM_K50_seed42.txt
✅ ECRTM OK: YahooAnswer_ECRTM_K100_seed42.mat -> /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/ECRTM/palmetto_CV_YahooAnswer_ECRTM_K100_seed42.txt

✅ Terminé. Résultats dans:
  LDA   → /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/LDA
  ECRTM → /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/ECRTM

Pour chaque modèle LDA / ECRTM, le code lit la matrice beta dans le .mat.

Il en extrait les TOPN mots les plus probables de chaque topic et les écrit dans un fichier texte.
Il lance Palmetto (programme Java) sur ces fichiers de topics pour calculer la cohérence C_V.
Il enregistre les scores retournés par Palmetto dans un fichier .txt de métriques pour chaque modèle.

In [36]:
import os
import numpy as np
import pandas as pd

OUT_DIR = "/Users/hydersidra/Documents/Master/PPD/ECRTM_runs"
OUT_DIR_LDA   = f"{OUT_DIR}/LDA"
OUT_DIR_ECRTM = f"{OUT_DIR}/ECRTM"

DATASET = "YahooAnswer"  

configs = [
    ("LDA",   20, 42, OUT_DIR_LDA),
    ("LDA",   50, 42, OUT_DIR_LDA),
    ("LDA",  100, 42, OUT_DIR_LDA),
    ("ECRTM", 20, 42, OUT_DIR_ECRTM),
    ("ECRTM", 50, 42, OUT_DIR_ECRTM),
    ("ECRTM",100, 42, OUT_DIR_ECRTM),
]

rows = []

for model, K, seed, folder in configs:
    fn = f"palmetto_CV_{DATASET}_{model}_K{K}_seed{seed}.txt"
    path = os.path.join(folder, fn)
    
    if not os.path.isfile(path):
        print(f" MANQUANT: {path}")
        continue
    
    print(f" Lecture: {fn}")
    
    vals = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            
            if not line or "INFO" in line or "ERROR" in line or line.startswith("2026-"):
                continue
            
          
            parts = line.split('\t')
            
            if len(parts) >= 2:
                score_str = parts[1].replace(',', '.')
                try:
                    score = float(score_str)
                    vals.append(score)
                except ValueError:
                    pass
    
    if not vals:
        print(f" Aucun score trouvé dans {fn}")
        continue
    
    vals = np.array(vals, dtype=float)
    
    rows.append({
        "model": model,
        "K": K,
        "seed": seed,
        "CV_mean": float(vals.mean()),
        "CV_std": float(vals.std(ddof=1)) if len(vals) > 1 else 0.0,
        "CV_min": float(vals.min()),
        "CV_max": float(vals.max()),
        "n_topics": len(vals),
    })

if not rows:
    print("\n Aucun score C_V trouvé.")
else:
    df_cv = pd.DataFrame(rows).sort_values(["model", "K"])
    
   
    out_csv = os.path.join(OUT_DIR, f"CV_summary_{DATASET}.csv")
    df_cv.to_csv(out_csv, index=False)
    
    print(f"\n Résumé sauvegardé: {out_csv}\n")
    print(df_cv.to_string(index=False))

 Lecture: palmetto_CV_YahooAnswer_LDA_K20_seed42.txt
 Lecture: palmetto_CV_YahooAnswer_LDA_K50_seed42.txt
 Lecture: palmetto_CV_YahooAnswer_LDA_K100_seed42.txt
 Lecture: palmetto_CV_YahooAnswer_ECRTM_K20_seed42.txt
 Lecture: palmetto_CV_YahooAnswer_ECRTM_K50_seed42.txt
 Lecture: palmetto_CV_YahooAnswer_ECRTM_K100_seed42.txt

 Résumé sauvegardé: /Users/hydersidra/Documents/Master/PPD/ECRTM_runs/CV_summary_YahooAnswer.csv

model   K  seed  CV_mean   CV_std  CV_min  CV_max  n_topics
ECRTM  20    42 0.371946 0.059974 0.21740 0.46958        20
ECRTM  50    42 0.402173 0.088469 0.23892 0.67203        50
ECRTM 100    42 0.386054 0.081806 0.21311 0.59807       100
  LDA  20    42 0.342713 0.073870 0.25550 0.49704        20
  LDA  50    42 0.350948 0.066223 0.24601 0.52937        50
  LDA 100    42 0.355209 0.060193 0.23979 0.50513       100

In [41]:
import pandas as pd

data = {
    'Modèle': ['ECRTM', 'ECRTM', 'LDA', 'LDA'],
    'K': [50, 100, 50, 100],
    'Notre CV Mean': [0.402, 0.386, 0.350, 0.355],
    'Papier CV Mean': [0.405, 0.389, 0.359, 0.359],
}

df = pd.DataFrame(data)

df['Écart'] = (df['Notre CV Mean'] - df['Papier CV Mean']).round(3).apply(lambda x: f"{x:+.3f}")
df['Notre CV Mean'] = df['Notre CV Mean'].round(3)
df['Papier CV Mean'] = df['Papier CV Mean'].round(3)

df_display = df[['Modèle', 'K', 'Notre CV Mean', 'Papier CV Mean', 'Écart']]
df_display

  Modèle    K  Notre CV Mean  Papier CV Mean   Écart
0  ECRTM   50          0.402           0.405  -0.003
1  ECRTM  100          0.386           0.389  -0.003
2    LDA   50          0.350           0.359  -0.009
3    LDA  100          0.355           0.359  -0.004

In [24]:
ls -lh /Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM/data/

total 0
drwxr-xr-x@ 10 hydersidra  staff   320B 26 jan 11:15 20NG/
drwxr-xr-x@ 10 hydersidra  staff   320B 26 jan 11:15 AGNews/
drwxr-xr-x@ 10 hydersidra  staff   320B 26 jan 11:15 IMDB/
drwxr-xr-x@  5 hydersidra  staff   160B 26 jan 11:15 stopwords/
drwxr-xr-x@ 10 hydersidra  staff   320B 26 jan 11:15 YahooAnswer/
drwxr-xr-x@ 10 hydersidra  staff   320B 26 jan 11:15 Yelp/

In [40]:
import os
import numpy as np
import pandas as pd
import scipy.io
from sklearn.metrics import normalized_mutual_info_score

#  CHEMINS 
PROJECT_DIR = "/Users/hydersidra/Documents/Master/PPD/ECRTM_project"
OUT_DIR = "/Users/hydersidra/Documents/Master/PPD/ECRTM_runs"

OUT_DIR_LDA   = f"{OUT_DIR}/LDA"
OUT_DIR_ECRTM = f"{OUT_DIR}/ECRTM"

VOCAB_PATH  = "/Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM/data/YahooAnswer/vocab.txt"
LABELS_PATH = "/Users/hydersidra/Documents/Master/PPD/ECRTM_project/repo/ECRTM/data/YahooAnswer/test_labels.txt"

TOPN_TD = 15  # Topic Diversity sur top-25 mots (standard papiers)

#  DATA
with open(VOCAB_PATH, "r", encoding="utf-8") as f:
    vocab = [line.strip() for line in f if line.strip()]

y_true = np.loadtxt(LABELS_PATH, dtype=int)
print(f"Chargé: {len(vocab)} mots vocab, {len(y_true)} documents avec labels\n")

#  METRICS 
def topic_diversity_from_beta(beta, vocab, topn=25):
    """TD = proportion de mots uniques dans les top-N de tous les topics"""
    all_words = []
    for k in range(beta.shape[0]):
        top_idx = np.argsort(beta[k])[::-1][:topn]
        all_words.extend(vocab[i] for i in top_idx)
    return len(set(all_words)) / max(1, len(all_words))

def purity_score(y_true, y_pred):
    """Purity = proportion de docs dans le cluster majoritaire pour chaque cluster"""
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    purity = 0
    for c in np.unique(y_pred):
        idx = np.where(y_pred == c)[0]
        if len(idx) == 0:
            continue
        _, counts = np.unique(y_true[idx], return_counts=True)
        purity += counts.max()
    return purity / len(y_true)

def find_theta_in_mat(d, K, N):
    """Cherche la matrice doc-topic (N, K) dans le .mat"""
    skip = {"__header__", "__version__", "__globals__"}
    for name, arr in d.items():
        if name in skip or not isinstance(arr, np.ndarray) or arr.ndim != 2:
            continue
        if arr.shape == (N, K):
            return name, arr
        if arr.shape == (K, N):
            return name, arr.T
    raise ValueError(f"Theta (doc-topic) introuvable. Clés disponibles: {list(d.keys())}")

#  CONFIG 
configs = [
    ("LDA",   20, 42, OUT_DIR_LDA),
    ("LDA",   50, 42, OUT_DIR_LDA),
    ("LDA",  100, 42, OUT_DIR_LDA),
    ("ECRTM", 20, 42, OUT_DIR_ECRTM),
    ("ECRTM", 50, 42, OUT_DIR_ECRTM),
    ("ECRTM",100, 42, OUT_DIR_ECRTM),
]

rows = []

for model, K, seed, folder in configs:
    fn = f"YahooAnswer_{model}_K{K}_seed{seed}.mat"
    mat_path = os.path.join(folder, fn)
    
    if not os.path.isfile(mat_path):
        print(f" MANQUANT: {mat_path}")
        continue
    
    print(f" Lecture: {fn}")
    
    d = scipy.io.loadmat(mat_path)
    beta = d["beta"]  # (K, V)
    
    # Trouver theta (doc-topic)
    try:
        theta_key, theta = find_theta_in_mat(d, K, len(y_true))
    except ValueError as e:
        print(f" Erreur pour {fn}: {e}")
        continue
    
    # Clustering: chaque doc assigné au topic dominant
    y_pred = theta.argmax(axis=1)
    
    # Métriques
    td = topic_diversity_from_beta(beta, vocab, topn=TOPN_TD)
    purity = purity_score(y_true, y_pred)
    nmi = normalized_mutual_info_score(y_true, y_pred)
    
    rows.append({
        "model": model,
        "K": K,
        "seed": seed,
        "TD": round(td, 4),
        "Purity": round(purity, 4),
        "NMI": round(nmi, 4),
    })

#  SAVE & DISPLAY
if not rows:
    print("\nAucune métrique calculée.")
else:
    df = pd.DataFrame(rows).sort_values(["model", "K"])
    
    # ← CHANGÉ : nom du CSV avec DATASET
    out_csv = os.path.join(PROJECT_DIR, "metrics", f"TD_Purity_NMI_{DATASET}.csv")
    os.makedirs(os.path.dirname(out_csv), exist_ok=True)
    df.to_csv(out_csv, index=False)
    
    print(f"\nRésumé sauvegardé: {out_csv}\n")
    print(df.to_string(index=False))

Chargé: 5000 mots vocab, 2500 documents avec labels

 Lecture: YahooAnswer_LDA_K20_seed42.mat
 Lecture: YahooAnswer_LDA_K50_seed42.mat
 Lecture: YahooAnswer_LDA_K100_seed42.mat
 Lecture: YahooAnswer_ECRTM_K20_seed42.mat
 Lecture: YahooAnswer_ECRTM_K50_seed42.mat
 Lecture: YahooAnswer_ECRTM_K100_seed42.mat

Résumé sauvegardé: /Users/hydersidra/Documents/Master/PPD/ECRTM_project/metrics/TD_Purity_NMI_YahooAnswer.csv

model   K  seed     TD  Purity    NMI
ECRTM  20    42 0.9967  0.5452 0.3185
ECRTM  50    42 1.0000  0.5288 0.2912
ECRTM 100    42 0.9080  0.5580 0.3077
  LDA  20    42 0.7133  0.4472 0.2542
  LDA  50    42 0.7440  0.4632 0.2485
  LDA 100    42 0.7400  0.4484 0.2317

In [42]:
import pandas as pd

data = {
    'Modèle': ['LDA', 'LDA', 'ECRTM', 'ECRTM'],
    'K': [50, 100, 50, 100],
    'TD Papier': [0.843, 0.602, 0.985, 0.903],
    'Pureté Papier': [0.288, 0.297, 0.550, 0.563],
    'NMI Papier': [0.144, 0.148, 0.295, 0.311],
    'Notre TD': [0.7440, 0.7400, 1.0000, 0.9080],  
    'Notre Pureté': [0.4632, 0.4484, 0.5288, 0.5580], 
    'Notre NMI': [0.2485, 0.2317, 0.2912, 0.3077]
}

df = pd.DataFrame(data)

df['Écart TD'] = (df['Notre TD'] - df['TD Papier']).round(3).apply(lambda x: f"{x:+.3f}")
df['Écart Pureté'] = (df['Notre Pureté'] - df['Pureté Papier']).round(3).apply(lambda x: f"{x:+.3f}")
df['Écart NMI'] = (df['Notre NMI'] - df['NMI Papier']).round(3).apply(lambda x: f"{x:+.3f}")

df_display = df[['Modèle', 'K', 'TD Papier', 'Pureté Papier', 'NMI Papier', 
                'Notre TD', 'Notre Pureté', 'Notre NMI', 'Écart TD', 'Écart Pureté', 'Écart NMI']]

df_display

,Modèle,K,TD Papier,Pureté Papier,NMI Papier,Notre TD,Notre Pureté,Notre NMI,Écart TD,Écart Pureté,Écart NMI
0,LDA,50,0.843,0.288,0.144,0.744,0.4632,0.2485,-0.099,+0.175,+0.105
1,LDA,100,0.602,0.297,0.148,0.740,0.4484,0.2317,+0.138,+0.151,+0.084
2,ECRTM,50,0.985,0.550,0.295,1.000,0.5288,0.2912,+0.015,-0.021,-0.004
3,ECRTM,100,0.903,0.563,0.311,0.908,0.5580,0.3077,+0.005,-0.005,-0.003

Le code lit les résultats LDA et ECRTM (les .mat).
Pour chaque modèle, il mesure à quel point les topics sont variés (TD) et alignés avec les vraies classes (Purity, NMI).